# Generated by Django 3.0.8 on 2020-07-25 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0003_auto_20200725_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='slug',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
