# Generated by Django 3.0.8 on 2020-07-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0006_auto_20200725_2123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='teams',
        ),
        migrations.AddField(
            model_name='class',
            name='teams',
            field=models.ManyToManyField(related_name='teams', to='class.Team'),
        ),
    ]
