# Generated by Django 3.0.8 on 2020-07-27 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0008_question_quiz_recordmark'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.CharField(max_length=30),
        ),
    ]
