# Generated by Django 3.0.8 on 2020-07-27 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class', '0009_auto_20200727_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='questions',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='value',
            field=models.FloatField(null=True),
        ),
    ]
